### ISSUE TITLE
Data type of timestamp field

### ISSUE THREAD

**Issue by chemerisuk** [louisbl/cordova-plugin-locationservices#12]
According to the spec (http://www.w3.org/TR/geolocation-API/#position_interface) the timestamp field of the Position object should have the Number, not Date data type.

**Comment by louisbl** [comment]
The spec said that the [timestamp field](http://www.w3.org/TR/geolocation-API/#timestamp) of the Position object must be represented as a DOMTimeStamp

> The timestamp attribute represents the time when the Position object was acquired and is represented as a DOMTimeStamp [DOMTIMESTAMP]. 

And in ECMAScript the [DOMTimeStamp](http://www.w3.org/TR/DOM-Level-3-Core/core.html#Core-DOMTimeStamp) is represented with the Date type

> For ECMAScript, DOMTimeStamp is bound to the Date type because the range of the integer type is too small.

So I assume the timestamp field is correctly represented with the Date type?

**Comment by chemerisuk** [comment]
@louisbl I do believe the spec is not fully clear on this part, because long and Date data types are completely different (value and ref). If you look at browser implementations - they use numeric value for this field. Therefore I'd suggest to do the plugin implementation is the consistent way with browsers.

**Comment by louisbl** [comment]
Agreed.

**Comment by chemerisuk** [comment]
@louisbl 
https://github.com/chemerisuk/cordova-plugin-locationservices/commit/4b55f39b62d02a2a8a5679ba9b706e926058c225 
https://github.com/chemerisuk/cordova-plugin-locationservices/commit/dfb7e277219d219294161b7dd325f244a68e5582

**Comment by louisbl** [comment]
I was looking at https://github.com/apache/cordova-plugin-geolocation/commit/cbdcedf056bbe8ee932b8542582520f6a3b4eca5#diff-4e76586a254c0011abe623baa80a266aR30

Not sure what's the best ;)

**Comment by louisbl** [comment]
I'll go with `Date.now()`, it's more explicit. Thanks for the tips!

**Comment by chemerisuk** [comment]
@louisbl FYI found NPE bug in my fork https://github.com/chemerisuk/cordova-plugin-locationservices/commit/dc7e1b2b40ce8f7abbe68859b8bac4f43ac24388

I believe your code is also affected by this bug.

**Comment by louisbl** [comment]
:+1: Thanks!
