### ISSUE TITLE
Unable to turn off the GPS

### ISSUE THREAD

**Issue by jul-m** [louisbl/cordova-plugin-locationservices#14]
Hello,

When I use the plugin, even with the options that active `enableHightAccucary:false` and `priority: cordova.plugins.locationServices.geolocation.priorities:PRIORITY_NO_POWER` the plugin still active gps, while information over the network enough for me in most cases. Besides the plugin sends me the value of the location via the network before the position via the GPS is available. Did I miss an option to force disable GPS ?

I use version 1.2.0 of the plugin with version 4.1.1 of cordova.

Thanks.

**Comment by louisbl** [comment]
Hi,

It seems that it's related to the Google Play Services, the plugin itself doesn't manage directly the GPS activation. I don't know if it's possible.

Maybe you could check the [Location Service doc](https://developers.google.com/android/reference/com/google/android/gms/location/package-summary) for more informations.

If you find something that needs to be changed in the plugin, feel free to re-open this issues.
