### ISSUE TITLE
Uncaught TypeError: LocationServices.lastPosition.timestamp.getTime is not a function

### ISSUE THREAD

**Issue by skourem** [louisbl/cordova-plugin-locationservices#15]
Hi! 

Thanks for your great plugin!

I am starting/stoping LocationServices via an ActivityRecognition service and sometimes (cannot reproduce it), I am getting this TypeError "LocationServices.lastPosition.timestamp.getTime is not a function" and LocationServices fail to start.

Plugin version: 1.2.0
Options:  {
                 enableHighAccuracy: true,
                 timeout : 12000,
                 maximumAge : 60000, 
                 priority: LocationServices.priorities.PRIORITY_BALANCED_POWER_ACCURACY,
                 interval: 10000, 
                 fastInterval: 5000
            }
Device: Samsung Duos Android 4.2

Could you please advise?

Thank you!

Regards,
Stelios

**Comment by louisbl** [comment]
Hi!

If you manage to reproduce it, would you mind sending me the stack trace.

Meanwhile I will check all calls to `getTime`, maybe I can find what's happening.

**Comment by skourem** [comment]
Thanks!
As a workaround, I replaced line 148 in LocationServices.js with 

`if (LocationServices.lastPosition && LocationServices.lastPosition.timestamp && LocationServices.lastPosition.timestamp.getTime && options.maximumAge && (((new Date()).getTime() - LocationServices.lastPosition.timestamp.getTime()) <= options.maximumAge)) {`

I don't know If it is a correct thing to do but for the last 2 days the issue hasn't been reproduced.

**Comment by louisbl** [comment]
OK, so it's indeed a bug in `v1.2.0`, it's been fixed in `v2.0.0`, where `timestamp` is always time in ms and not a Date object.
I'll make a `v1.2` branch a publish a new release.

**Comment by louisbl** [comment]
The new version compatible with Cordova 4 has been published:
`cordova plugin add cordova-plugin-locationservices@legacy`
