### ISSUE TITLE
watchPosition is returning undefined

### ISSUE THREAD

**Issue by flexarts** [louisbl/cordova-plugin-locationservices#16]
I am using cordova 6.0.0 and a default cordova project with just a call to `cordova.plugins.locationServices.geolocation.watchPosition(positionSuccess, positionFailed, geolocationOptions);`

The problem is that the API method watchPosition is returning `undefined` because the watchID is only generated asynchronously at the next tick. The solution here is just to generate the watchID in the synchronous API method and pass it forward to `LocationServicesWithoutPermission.watchPosition`.

I already fixed it for the project I work on but I will submit a new PR for this issue.

Cheers

**Comment by louisbl** [comment]
Thanks a lot!

I will release a new version with this patch.
