### ISSUE TITLE
Compatibility with Cordova Android 5.0.0

### ISSUE THREAD

**Issue by chemerisuk** [louisbl/cordova-plugin-locationservices#6]
Hey guys. Any plan to extend plugin with Android 6 permission model? I believe updated version of `cordova-plugin-geolocation` can be used as an example.

**Comment by louisbl** [comment]
@chemerisuk Would mind testing the v2.0.0 on a device with Android 6 before I push the new version on npm?

```
cordova plugin add https://github.com/louisbl/cordova-plugin-locationservices.git#v2.0.0
```

**Comment by chemerisuk** [comment]
@louisbl sure, as soon as I'll have an Android 6 device on my stand :)

**Comment by louisbl** [comment]
I assumed you have one because of your request :)
I have tested with the emulator so far, let's publish it.

**Comment by chemerisuk** [comment]
@louisbl do you need to update files in `www` folder as well? Check https://github.com/apache/cordova-plugin-geolocation/blob/master/www/android/geolocation.js

**Comment by louisbl** [comment]
Well, I have: https://github.com/louisbl/cordova-plugin-locationservices/commit/15e6cf6d1f40b5f85f5151d54b2c73eea913b2b4#diff-9476c6f523a2cc5655bf5d30bcc1bb2cL235
