### ISSUE TITLE
watchPosition/clearWatch broken

### ISSUE THREAD

**Issue by cvaliere** [louisbl/cordova-plugin-locationservices#9]
With message

<pre>ReferenceError: errorCallback is not defined
    at Object.LocationServices.watchPosition (LocationServices.js:251)</pre>

I think that, in LocationServices.js,
line 245

<pre>watchPosition: function(success, error, args) {</pre>

should be replaced by

<pre>watchPosition: function(successCallback, errorCallback, args) {</pre>

and same for clearWatch line 253

**Comment by louisbl** [comment]
Indeed. Would you mind opening a PR?

**Comment by cvaliere** [comment]
yup, done
